"
A PrismComponentStyleStrategyTest is a test class for testing the behavior of PrismComponentStyleStrategy
"
Class {
	#name : 'PrismComponentStyleStrategyTest',
	#superclass : 'PrismComponentStrategyTest',
	#category : 'PrismCodeDisplayer-Core-Tests',
	#package : 'PrismCodeDisplayer-Core-Tests'
}

{ #category : 'helpers' }
PrismComponentStyleStrategyTest >> actualClass [
	^ PrismComponentStyleStrategy
]
