as yet unclassified
sourceCode: aSourceText linkObjects: aCollectionOfObject linkPositionFunction: aFunctionReturningInterval callBack: aBlockToExecture linkStyle: aStyleCssClass language: aCodeLanguage
	^ self new
		sourceCode: aSourceText;
		linkObjects: aCollectionOfObject;
		linkPositionFunction: aFunctionReturningInterval;
		callBack: aBlockToExecture;
		linkStyle: aStyleCssClass;
		language: aCodeLanguage;
		yourself